spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://yapdev.cclnjigf9cpr.ap-northeast-2.rds.amazonaws.com/yapdev
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: wonwoo8
      password: 1712wonwoo
server:
  servlet:
    encoding:
      charset: UTF-8