spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/yapyap
      driver-class-name: org.h2.Driver  
      username: sa
      password:
server:
  servlet:
    encoding:
      charset: UTF-8